workspace:
  base: /test
  path: ecl-twig-loader

services:
  web:
    image: ${IMAGE_PHP=fpfis/httpd-php-ci:7.1}
    environment:
    - DOCUMENT_ROOT=/test/ecl-twig-loader

pipeline:
  composer-install-lowest:
    group: prepare
    image: ${IMAGE_PHP=fpfis/httpd-php-ci:7.1}
    volumes:
    - /cache:/cache
    commands:
    - composer update --prefer-lowest --ansi
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: ${IMAGE_PHP=fpfis/httpd-php-ci:7.1}
    volumes:
    - /cache:/cache
    commands:
    - composer install --ansi
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-ci:7.1}
    commands:
    - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-ci:7.1}
    commands:
    - ./vendor/bin/phpunit

matrix:
  IMAGE_PHP:
  - fpfis/httpd-php-ci:7.1
  COMPOSER_BOUNDARY:
  - lowest
  - highest
